name: Build
on:
  workflow_dispatch:

env:
  CHANNEL_LINK: "pear://3ysp1rtmrcmbinxk4ossegdx8hm85ptksdmo3u5xq3iwsmshtspy"
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: linux
            arch: x64
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: build/_drive
          key: corestore-${{ matrix.platform }}-${{ matrix.arch }}${{ matrix.tags }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: |
          sudo apt-get update
          sudo apt-get install -y curl ca-certificates build-essential git libgtk-4-dev pkg-config fuse file
          # sudo apt-get install -y clang pkg-config libgtk-4-dev clang-tools fuse file
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          npm install --install-links --legacy-peer-deps
        if: ${{ matrix.platform == 'linux' }}
      - run: sudo apt install libatomic1
        if: ${{ matrix.platform == 'linux' }}
      - run: choco upgrade llvm
        if: ${{ matrix.platform == 'win32' }}
      - run: choco install nasm
        if: ${{ matrix.platform == 'win32' }}
      - run: npm install -g pear
      - run: npm install -g bare-make
      - run: npm run install:all
      - name: "Stage to channel"
        run: |
          echo "CHANNEL_LINK: ${CHANNEL_LINK}"
          pear stage --ignore .git --no-ask ${CHANNEL_LINK} 
      - name: "Show bare-make version"
        run: bare-make --version
      - name: "Generate appling linux "
        working-directory: ./appling
        run: bare-make generate --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}
      - name: "Build appling"
        working-directory: ./appling
        run: bare-make build
      - name: Find & rename AppImage file
        id: find_file
        run: |
          set -euo pipefail
          APPIMAGE_PATH=$(find "$GITHUB_WORKSPACE" -name "*.AppImage" -type f | head -n 1)
          echo "Original AppImage: $APPIMAGE_PATH"

          NEW_NAME="Oniri-Desktop-Linux-${{ matrix.arch }}-v1.AppImage"
          NEW_PATH="$GITHUB_WORKSPACE/$NEW_NAME"

          mv "$APPIMAGE_PATH" "$NEW_PATH"
          echo "Renamed AppImage to: $NEW_PATH"

          echo "APPIMAGE_PATH=$NEW_PATH" >> "$GITHUB_OUTPUT"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT
        if: ${{ matrix.platform == 'linux' }}
      - name: Find & rename Win file
        id: find_file_win
        run: |
          set -euo pipefail
          APPIMAGE_PATH=$(find "$GITHUB_WORKSPACE" -name "*.exe" -type f | head -n 1)
          echo "Original AppImage: $APPIMAGE_PATH"

          NEW_NAME="Oniri-Desktop-Win-${{ matrix.arch }}-v1.exe"
          NEW_PATH="$GITHUB_WORKSPACE/$NEW_NAME"

          mv "$APPIMAGE_PATH" "$NEW_PATH"
          echo "Renamed AppImage to: $NEW_PATH"

          echo "APPIMAGE_PATH=$NEW_PATH" >> "$GITHUB_OUTPUT"

          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_OUTPUT
        if: ${{ matrix.platform == 'win32' }}
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.platform == 'linux' && steps.find_file.outputs.APPIMAGE_PATH != '' }}
        with:
          name: Oniri-Desktop-Linux-${{ matrix.arch }}-v1.AppImage
          path: "${{ steps.find_file.outputs.APPIMAGE_PATH }}"
      - uses: actions/upload-artifact@v4
        if: ${{ matrix.platform == 'win32' && steps.find_file_win.outputs.APPIMAGE_PATH != ''}}
        with:
          name: Oniri-Desktop-Windows-${{ matrix.arch }}-v1
          path: ${{ steps.find_file_win.outputs.APPIMAGE_PATH }}

  merge:
    runs-on: ubuntu-latest
    needs: prebuild
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: install
          merge-multiple: true
      - uses: actions/upload-artifact@v4
        with:
          name: builds
          path: install
          retention-days: 1